name: Report WTM Issue
description: Report Wireless Traffic Management system problems
title: "[WTM] Short issue description"
labels: [bug, wtm-issue, status:open]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## WTM Issue Report
        Please fill out this form completely for WTM system issues.

  - type: input
    id: affected_zone
    attributes:
      label: 🛠️ Affected Component
      description: Which zone is affected? (e.g., Z1, Z2, Z3)
      placeholder: "Z1"
    validations:
      required: false

  - type: input
    id: affected_column
    attributes:
      label: 📊 Affected Column
      description: Which column is affected? (e.g., C1, C2, C3)
      placeholder: "C1"
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: 🛠️ Affected Component
      description: Select the affected WTM component
      options:
        - Zone
        - ZTC
        - Bridge Master
        - Bridge Slave
        - Power Supply
        - Power Cable
        - CAN Bus
        - FRC Cable
        - OTA
        - Mounting Plate
        - Mechanical Assembly
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue_category
    attributes:
      label: 📂 Issue Category
      description: Primary category of the issue
      options:
        - Mechanical
        - Electronics
        - Embedded
        - Software
    validations:
      required: true

  - type: dropdown
    id: component_status
    attributes:
      label: ⚙️ Component Status
      description: Current state of the affected component
      options:
        - Non-functional (completely down)
        - Intermittent (works sometimes)
        - Degraded (reduced performance)
        - Error state (shows errors but working)
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: 📝 Issue Description
      description: Clearly describe the problem observed
      placeholder: "Describe symptoms, error messages, communication failures, etc."
    validations:
      required: true

  - type: dropdown
    id: clarity
    attributes:
      label: Clarity of the Issue
      description: How well-defined and reproducible is this issue?
      options:
        - Poor
        - Good
        - Excellent
    validations:
      required: true

  - type: input
    id: issue_start_time
    attributes:
      label: 🔍 Clarity of the Issue
      description: When did this issue first occur? (YYYY-MM-DD HH:MM format)
      placeholder: "2025-11-12 14:30"
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 🔁 Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Power on the zone
        2. Observe communication failure
        3. Check error logs
    validations:
      required: false

  - type: input
    id: code_release_id
    attributes:
      label: 🏷️ Code Release ID
      description: Firmware/software version running on the system
      placeholder: "11_Release_1701_17JUN25"
    validations:
      required: false

  - type: textarea
    id: error_logs
    attributes:
      label: 🧾 Error Logs / Screenshots
      description: Paste error logs, network diagnostics, or attach screenshots
      placeholder: "Paste logs here or drag and drop images"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 Priority
      description: Severity of this issue
      options:
        - P1 - Critical (Bot Down, blocking operations)
        - P2 - Important (Major impact, workaround available)
        - P3 - Minor (Minor impact, scheduled fix)
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 📘 Additional Context
      description: Any other relevant information
      placeholder: "Recent changes, environmental factors, related issues, etc."
    validations:
      required: false
